### ISSUE TITLE
Error installing 0.8.3.beta on Ubuntu

### ISSUE THREAD

**Issue by gmeader** [mikacousin/olc#20]
Following instructions in README on github:

$ sudo ninja -C builddir install
ninja: Entering directory `builddir'
[0/1] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 564, in do_install
    d = self.check_installdata(pickle.load(ifile))
AttributeError: Can't get attribute 'RunScript' on <module 'mesonbuild.build' from '/usr/lib/python3/dist-packages/mesonbuild/build.py'>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

**Comment by mikacousin** [comment]
I don't know what version of Ubuntu you're using but there seems to be something wrong with the olc install script.

I did a quick test with Ubuntu in a virtual machine, meson finishes without error but olc doesn't install where it should.

I'll look for a solution when I have time.

In the meantime, you can install the version available on [flathub](https://flathub.org/apps/com.github.mikacousin.olc) which should work on all distributions.

**Comment by mikacousin** [comment]
Finally, I did more tests with Ubuntu and it works.
Now you can install ola with apt, I've updated the readme accordingly.

Have you found the source of your problem with meson?

**Comment by gmeader** [comment]
I don't know anything about Meson. I was just trying to install and run the
app on a fully updated Lubuntu laptop.
Further: I'd like to install the source code for olc into PyCharm and run
it from there.
However, you've got a bunch of build automation that I guess I need to
decipher before I can do that...
I don't know enough about large Python apps, packaging, modules, etc.

**Comment by mikacousin** [comment]
Hello,
I installed the latest Lubuntu in a virtual machine and olc was installed without error.
I really have no idea what your problem is, sorry.

I don't think you can launch the application directly from PyCharm. To do that, olc would have to be launched without installation, which requires work that I personally don't have the time or interest to do.
But as with any free project, all contributions are welcome :-)

I'll keep this issue open but I'll close it in a little while
